version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: skillify_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skillifydb
      MYSQL_USER: skillifyuser
      MYSQL_PASSWORD: skillifypass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
