spring.application.name=skillify
#spring.datasource.url=jdbc:mariadb://localhost:3306/skillifydb
#spring.datasource.username=skillifyuser
#spring.datasource.password=skillifypass
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secret-key=your-256-bit-secret-key-here
application.security.jwt.expiration=86400000