# Application name
spring.application.name=skillify

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/skillifydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console Configuration (optional, for accessing the H2 console)


# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
application.security.jwt.secret-key=vF8gJ5U2Vn9pYqZ3q8NdPzWbGzF6Xt5+JNRVh4J3hWY=
application.security.jwt.expiration=86400000


#Actuator 
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true

#Performance
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=2000
spring.task.execution.pool.rejection-policy=caller-runs
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.tomcat.threads.max=500
server.tomcat.threads.min-spare=20

#JPA
spring.jpa.properties.hibernate.cache.use_second_level_cache=false #true
#spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
spring.jpa.properties.hibernate.jdbc.batch_size=30