# Application name
spring.application.name=skillify
server.port=8082

# H2 Database Configuration (File-based)
spring.datasource.url=jdbc:h2:file:./data/temm_ead;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
application.security.jwt.secret-key=vF8gJ5U2Vn9pYqZ3q8NdPzWbGzF6Xt5+JNRVh4J3hWY=
application.security.jwt.expiration=86400000


#Actuator 
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true

#Performance
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=2000
spring.task.execution.pool.rejection-policy=caller-runs
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.tomcat.threads.max=500
server.tomcat.threads.min-spare=20

#JPA
spring.jpa.properties.hibernate.cache.use_second_level_cache=false #true
#spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
spring.jpa.properties.hibernate.jdbc.batch_size=30


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#AWS
aws.accessKeyId=1aa131e4bcb24ea1b63959c6fe9ee24d
aws.secretAccessKey=3882b2d9b0a468e9b331587d3992597d
aws.region=default
aws.s3.bucket=ead
aws.s3.endpoint=https://usc1.contabostorage.com

imagekit.publicKey=your_imagekit_public_key
imagekit.privateKey=private_9Mh6MZBcyyUFVvskC9wU8/Gh6GU=
imagekit.urlEndpoint=https://ik.imagekit.io/your_id